Fix doxygen
pdidev/pdi pull request #510
Opened 2024-12-19 10:51 UTC by jbigot

Fix doxygen website generation

# List of things to check before making a PR

Before merging your code, please check the following:

* [x] you have added a line describing your changes to the Changelog;
* [x] you have added unit tests for any new or improved feature;
* [x] In case you updated dependencies, you have checked pdi/docs/CheckList.md
* you have checked your code format:
  - [x] you have checked that you respect all conventions specified in CONTRIBUTING.md;
  - [x] you have checked that the indentation and formatting conforms to the `.clang-format`;
  - [x] you have documented with doxygen any new or changed function / class;
* you have correctly updated the copyright headers:
  - [x] your institution is in the copyright header of every file you (substantially) modified;
  - [x] you have checked that the end-year of the copyright there is the current one;
* you have updated the AUTHORS file:
  - [x] you have added yourself to the AUTHORS file;
  - [x] if this is a new contribution, you have added it to the AUTHORS file;
* you have added everything to the user documentation:
  - [x] any new CMake configuration option;
  - [x] any change in the yaml config;
  - [x] any change to the public or plugin API;
  - [x] any other new or changed user-facing feature;
  - [x] any change to the dependencies;
* you have correctly linked your MR to one or more issues:
  - [x] your MR solves an identified issue;
  - [x] your commit contain the `Fix #issue` keyword to autoclose the issue when merged.

2025-01-07 17:20 UTC, jmorice91 requested changes
Add something to help the user to build the documentation

2025-01-07 17:20 UTC, jmorice91 commented on pdi/docs/CMakeLists.txt
We have a compilation error with BUILD_DOCUMENTATION=ON, if we don't have the README.txt of the tutorial repository ("${PDI_SOURCE_DIR}/../tutorial/README.md"). 

I suggest to add a comment on the installation guide to help the user to build the documentation.

2025-01-07 17:20 UTC, jmorice91 commented on pdi/docs/Doxyfile
> +DOT_PATH               = /usr/bin
Perhaps, can be os dependent?

2025-01-09 08:20 UTC, benoitmartin88 requested changes
Update copyright dates to 2025.

2025-01-09 08:20 UTC, benoitmartin88 commented on pdi/docs/Doxyfile
> +# Copyright (C) 2024 Commissariat a l'energie atomique et aux energies alternatives (CEA)
```suggestion
# Copyright (C) 2025 Commissariat a l'energie atomique et aux energies alternatives (CEA)
```

2025-01-09 08:32 UTC, jbigot commented on pdi/docs/Doxyfile
> +# Copyright (C) 2024 Commissariat a l'energie atomique et aux energies alternatives (CEA)
I believe this was done in 2024 :)

2025-01-09 08:33 UTC, jbigot commented on pdi/docs/Doxyfile
> +DOT_PATH               = /usr/bin
indeed, I took the one generated by cmake, but this is likely something to extract from somewhere, let me check

2025-01-22 11:15 UTC, JAuriac commented
Maybe also check the CI pipeline for [workflows/pages.yml](https://github.com/pdidev/pdi/blob/9b5c0dc802c5b262bd95fe70d05c3fa7caba8e77/.github/workflows/pages.yml), which is still using Ubuntu 20.04.

2025-01-22 13:29 UTC, Yushan-Wang approved these changes
good to go

2025-01-22 15:13 UTC, JAuriac approved these changes

2025-01-23 05:39 UTC, merged